packages:
  FloatingPanel:
    url: https://github.com/scenee/FloatingPanel
    version: 1.6.4
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    version: 6.1.4
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs
    from: 8.0.0
